# Header for the top of a processed file. This is modified from Numpy's
# distutils.
header =\
"""
/*
 *****************************************************************************
 **       This file was autogenerated from a template  DO NOT EDIT!         **
 **       Changes should be made to the original source (.src) file         **
 *****************************************************************************
 */

"""

def parse_head():
    """
    Gets the information from the header of a loop section.

    """
